credentials:
  usernames:
    admin:
      email: admin@rlv.com
      name: RLV Admin
      password: admin123

cookie:
  expiry_days: 7
  key: some_signature_key
  name: rlv_portal_cookie

preauthorized:
  emails:
    - admin@rlv.com
    
